server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8080

spring:
    # mysql
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            url: jdbc:mysql://39.108.222.60:3306/campus?useUnicode=true&characterEncoding=UTF-8
            username: hp
            password: root
            driver-class-name: com.mysql.jdbc.Driver
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
        static-locations: classpath:/
    freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: true
        charset: utf-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        prefix: /templates/
        suffix: .ftl
        template-loader-path: classpath:/templates/
    mvc:
        date-format: yyyy-MM-dd HH:mm:ss
        view:
            prefix: /templates/
            suffix: .ftl
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
logging:
    level.com.legend: DEBUG
