server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8080

spring:
    # mysql
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://39.108.222.60:3306/campus?useUnicode=true&characterEncoding=UTF-8
        username: hp
        password: root
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
        static-locations: classpath:/
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
logging:
    level.com.legend: DEBUG
